### ISSUE TITLE
Don't break native momentum scrolling

### ISSUE THREAD

**Issue by bfred-it** [idiotWu/smooth-scrollbar#14]
Some devices already offer smooth momentum scrolling, this script shouldn't interfere with that because native behavior is unmatchable (i.e. momentum overscroll) and scripts like this degrade the experience rather than improve it.

My suggestion is to detect the delta and if it's already low, detach `WHEEL_EVENT` or don't `.preventDefault()`

**Comment by idiotWu** [comment]
However we could not tell whether it's momentum scrolling from delta value. I thought of this issue before but Javascript seems to be too weak to resolve it. So all that I can do is to simulate native momentum scrolling.

If you get some clues about it, please show me a working snippet or create a PR :)

**Comment by idiotWu** [comment]
Well experimental overscroll effect is supported since version [6.0.0](https://github.com/idiotWu/smooth-scrollbar/releases/tag/v6.0.0). 

And to active native overscroll, you just need to set `continuousScrolling: true` and `overscrollEffect: false` to enable event propagation when it's scrolling to very edge of container (this is supposed to be supported since version 5.2.0, I'm a little confused about how this issue comes).

Anyway I think we can close this issue now, for further discussion on native scrolling please view issue #27.
