### ISSUE TITLE
Scrolling track offset

### ISSUE THREAD

**Issue by martinsnajdr** [idiotWu/smooth-scrollbar#166]
Is there any way how to make the scrolling track with top & bottom offset? I tried to change the style with CSS – but the thumb still thinks the track is 100% height of the scrolling wrapper. The thumb starts ok at the top (with the offset), but it goes beyond the bottom offset.

Thanks.

**Comment by idiotWu** [comment]
I'm afraid it's not possible now, and there might never be a plan for that. I'd suggest you remove the default tracks then implement one yourself.

**Comment by GiorgosXou** [comment]
**I don't know why this issue is still labeled as wontfix but what i found to work for me as an offset *(if anyone is looking for just-an-instant-work-around-way)*, was just to:**

* 🦘 **Jump-To** *`".\smooth-scrollbar\track\thumb.js"`*
* ➕ **Add**  *`"containerSize -= 96;  pageSize -= 96;"`* lines under the *`"..update(..){.."`*  function (where 96 your offset)
* 🦘 **Then Jump-To** your css (where 15 and 115 your offsets)
* ➕ **Add**  *`".scrollbar-track{  top:15px;   height: calc(100vh - 115px) !important; }"`*
* ✔️ and  **Done**.

PS. not the best way but it works like a charm for now [(screenshot)](https://prnt.sc/v35eik)
