### ISSUE TITLE
scrollbars not visible on init

### ISSUE THREAD

**Issue by alexisargyris** [idiotWu/smooth-scrollbar#19]
So, I start with some html like this:

```
<scrollbar>
  <div>some long content</div>
</scrollbar>

```
and I init it like this:

`Scrollbar.initAll();
`

The resultant dom elements look like this:

```
<scrollbar data-scrollbar tabindex="1" class style="overflow: hidden; outline: none;">
  <article class="scroll-content">
    <div>some long content</div>
  <article>
  <aside class="scrollbar-track scrollbar-track-x" style="display: none;">...</aside>
  <aside class="scrollbar-track scrollbar-track-y" style="display: none;">...</aside>
</scrollbar>

```

I import `smooth-scrollbar.css`. The browser window is small so the scrollbars should be visible. Any idea what I should do?

**Comment by idiotWu** [comment]
To make scrollbar work, you should make sure that parent element, or we say scrollbar container, has a certain height and/or width so that the content inside it can be scrollable. Just like what you do to make real scrollbar works.

Here is a working demo: http://jsbin.com/gurukew/1/edit?html,css,js,output

**Comment by alexisargyris** [comment]
that was really useful, thanks
