### ISSUE TITLE
Does not work event "keydown/down" on loaded page, before onclick page :(

### ISSUE THREAD

**Issue by veniaminryadnov** [idiotWu/smooth-scrollbar#292]
## Environment
- Browser: Chrome
- Version of smooth-scrollbar: 8.5.2

## Issue Summary
After loading the page, if you press the down button, the page will not scroll until you click on the page.

## Expected Behavior
After loading the page, if you press the button down, the page scrolls without any mouse click on the page itself

![Video-20201216-165701-669](https://user-images.githubusercontent.com/17233036/102358183-4511d780-3fc0-11eb-9367-e4725397b361.gif)

**Comment by idiotWu** [comment]
Keyboard events require the scrollbar container to be focused, otherwise we have no idea about which one to scroll (the keyboard events may be fired from child elements/nested scrollbars). See: 

https://github.com/idiotWu/smooth-scrollbar/blob/17ce0196c0fdce5bdceda8ef5316e705e0f62d30/src/events/keyboard.ts#L27-29
