### ISSUE TITLE
Scroll inside fixed element?

### ISSUE THREAD

**Issue by maxvia87** [idiotWu/smooth-scrollbar#296]
<img width="942" alt="Screen Shot 2021-01-20 at 02 44 01" src="https://user-images.githubusercontent.com/64636974/105115831-dd244480-5ac9-11eb-890e-8b9dbfcfb4b3.png">

Hi,

When I init a Scrollbar I am unable to scroll on the div on the left unless my Scrollbar reaches the top or bottom? 

How do we handle scrolling inside a fixed div? 

I was looking for answers but couldnt find anything that fit my pb.

Thank you for the help and great library !

**Comment by idiotWu** [comment]
You can use the `delegateTo` option to delegate wheel/touch events to another element. For your case, you can set `delegateTo: document` so that all the wheel/touch events will be handled at `document` level.

See: https://github.com/idiotWu/smooth-scrollbar/blob/develop/docs/README.md#available-options-for-scrollbar

**Comment by maxvia87** [comment]
Grea! Thank you
