### ISSUE TITLE
Doesnt work in IE11 on Windows Surface

### ISSUE THREAD

**Issue by wejn1** [idiotWu/smooth-scrollbar#39]
## Issue Summary

The demo page doesnt work in IE11 when I tried testing it on a Windows Surface.
## Expected Behavior

demo page
## Current Behavior

shows upper part of the website without the ability to scroll down.
## Steps to Reproduce

Open the demo page in IE11 on a Windows Surface
## Environment
- Browser: Internet Explorer 11
- OS: Windows 10 Home
- Version of smooth-scrollbar: -

**Comment by idiotWu** [comment]
Sorry I am not able to test on IE mobile :(

**Comment by AntoineBoulanger** [comment]
IE doesn't support touch events. You can add pointer events to make it work in IE or add a touch events polyfill.

Also, you can't scroll with some trackpads in IE and Edge because wheel events don't work. I don't know how this one could be fixed. https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7134034/

**Comment by idiotWu** [comment]
@AntoineBoulanger thanks for the useful information. But I'm afraid introducing pointer events API is not that easy because:

1. Pointer events API provides an absolutely different interface from touch events, which means we may have to start over.

2. It requires an additional polyfill.

I'm looking for a workaround to the touch events issue 😃

**Comment by idiotWu** [comment]
Hey I've just found something interesting from hakimel/reveal.js#450. It appears that all we need to do is to set `msTouchAction` to `'none'` on the container element. 

Can anyone helps me to test this black magic?
