### ISSUE TITLE
hey bro, im hiding my default cursor on my landing pages and costomize it with another div so its position is absolute ,  when i did render ur package it seems my cursor is moving somehow late , means the position cant follow the mouse position , help please

### ISSUE THREAD

**Issue by salemsifeddine** [idiotWu/smooth-scrollbar#429]
## Environment
- Browser:
- Version of smooth-scrollbar:

**Comment by idiotWu** [comment]
Any demo here?

**Comment by idiotWu** [comment]
Closed as no response.

**Comment by salemsifeddine** [comment]
https://beliedelice.herokuapp.com/ ,, look at the cookie in the middle of the page it should be splited but when i added ur librrary it doesn't

**Comment by sadeghbarati** [comment]
Virtual Scroll !== Native Scroll

It's not working because it's `virtual` not a real scrollbar
you have to do it with smooth-scrollbar api

it's your code:
```js
$(window).on("scroll",function(e){
    valueS = $(this).scrollTop();
    
    if(valueS <= 420){
        leftBely.style.top='-'+ valueS / 3
        rightBely.style.top='+'+ valueS / 3
    }
})
```


**instead of code above**, use `smooth-scrollbar API` [addListener](https://github.com/idiotWu/smooth-scrollbar/blob/develop/docs/api.md#scrollbaraddlistener), [offset](https://github.com/idiotWu/smooth-scrollbar/blob/develop/docs/api.md#scrollbaroffset)
