### ISSUE TITLE
Scrollbar.limit.y calculated wrong

### ISSUE THREAD

**Issue by pttnx** [idiotWu/smooth-scrollbar#456]
### Checks

- [X] Not a duplicate.

### Version

8.7.4

### Description

** When scrolling down to the bottom of the page, the container seems to be longer, as it really is. When scrolling down again, the limit updates, but breaks other plugins functions. Page is using Barba for dynamic Content loading.** 

### Steps to Reproduce

1. Scroll down to the bottom - container is longer then it should
2. Scroll down again and the container height gets updated.

**Comment by idiotWu** [comment]
Not familiar with the library you are using, but I think manually call `scrollbar.update()` after contents changed would solve this issue.

**Comment by pttnx** [comment]
actually, this happens without switching the pages. Just found out this happens on both, top of the scroll-container and the bottom. I could provide a link to the stage if you would like to have a look.

**Comment by pttnx** [comment]
no, its simple scrolling. feel free to take a look:
https://schmidt.pttn.li/
user: stage
pw: st4ge!

**Comment by idiotWu** [comment]
Thanks for the demo!

It is the lazyload animation/transition that causes the problem. Images are transformed by `translateY(100%)` before loading and `translateY(0%)` after loaded, thus affecting the`scrollHeight`. The easiest way to fix this issue is to "clip" those content via:

```css
main {
  overflow: hidden;
}
``` 

FYI: this issue also occurs on native scrollbars as we are using the same mechanism to calculate dimensions

https://user-images.githubusercontent.com/6022672/156504800-3bd74c5d-be08-406d-bc2c-40ae9dfd4390.mp4

**Comment by pttnx** [comment]
that worked like a charm. thanks !
