### ISSUE TITLE
When a page contains a large smooth-scrollbar div, zoom not work

### ISSUE THREAD

**Issue by flyinghail** [idiotWu/smooth-scrollbar#59]
The page has a large scroll div, I found I cannot  zoom the page with two fingers on touch screen.

Similarly, on desktop browser,  zoom use ctrl + mouse wheel also not work.

**Comment by idiotWu** [comment]
Yeah, because the default behavior of touch event is prevented [here](https://github.com/idiotWu/smooth-scrollbar/blob/develop/src/events/touch.js#L87).

As for the desktop with mouse, since I don't even have a mouse so I am not able to know the exact behavior. But wheel event is not prevented so I think the zoom should work.
