### ISSUE TITLE
Option to set duration and callback to scrollIntoView

### ISSUE THREAD

**Issue by TomS-** [idiotWu/smooth-scrollbar#71]
## Issue Summary

Add the ability to add the duration and callback to scrollIntoView. I'm currently using scrollTo and $(this).offset().top + scrollbar.offset.y

**Comment by idiotWu** [comment]
This method is just similar to the native scrollIntoView method, so I am not about add more arguments to it.

Meanwhile, it's not possible to set scrolling duration because current easing equation is movement(n) = movement(n-1) * (1-damping), or m(n) = m(0) * (1-d)^n. When m(n) -> 0, the iteration count n only depends on initial movement m(0) (aka scrolling distance) and damping factor d. As both of the two factors are fixed, it's not possible to control the iteration count (aka animation frames count).

If you want to control the scrolling duration, use scrollTo() method instead, of which the easing curve is a quadratic function.
